Repository sveltejs/kit, pull requests merged in 2021-03, with the labels that each got.

#490 Do not build endpoint code for client
  .changeset/wild-cooks-drive.md
  packages/kit/src/core/build/index.js
Labels: bug, pkg:kit

#500 Start on a migration guide
  documentation/migrating/01-migrating.md
Labels: site / documentation

#483 adapter-vercel: Use CJS entrypoint to load ESM files
  .changeset/selfish-owls-own.md
  packages/adapter-vercel/index.js
  packages/adapter-vercel/rollup.config.js
  packages/adapter-vercel/src/entry.js
  packages/adapter-vercel/src/index.cjs
Labels: bug, pkg:adapters

#475 A handful of type fixes
  packages/kit/package.json
  packages/kit/src/core/build/index.js
  packages/kit/src/core/dev/index.js
  packages/kit/src/runtime/app/navigation.js
  packages/kit/src/runtime/client/renderer.js
  packages/kit/src/runtime/client/router.js
  packages/kit/src/runtime/client/singletons.js
  packages/kit/src/runtime/client/utils.js
  packages/kit/src/runtime/server/page.js
  packages/kit/src/types.d.ts
  packages/kit/tsconfig.all.json
  packages/kit/tsconfig.enforced.json
Labels: typescript

#526 Fix error handling when thrown type is not Error
  packages/kit/src/runtime/server/page.js
  packages/kit/src/types.d.ts
Labels: error handling

#539 Add page titles to demo site
  examples/svelte-kit-demo/src/routes/about/index.svelte
  examples/svelte-kit-demo/src/routes/blog/[slug].svelte
  examples/svelte-kit-demo/src/routes/blog/index.svelte
  examples/svelte-kit-demo/src/routes/index.svelte
Labels: pkg:examples

#558 Add some information about how to migrate integrations
  documentation/migrating/01-migrating.md
Labels: site / documentation

#445 typecheck in CI
  .github/workflows/ci.yml
  package.json
  packages/kit/src/core/dev/index.js
  packages/kit/src/core/load_config/index.js
  packages/kit/src/core/start/index.js
  packages/kit/src/runtime/server/index.js
  packages/kit/src/runtime/server/page.js
  packages/kit/types.d.ts
  packages/kit/types.internal.d.ts
Labels: typescript

#571 Add Vercel to list of adapters
  packages/create-svelte/template/README.md
Labels: site / documentation

#543 Update READMEs
  README.md
  packages/kit/README.md
Labels: site / documentation

#588 Fix adapter-vercel imports
  .changeset/new-birds-march.md
  packages/adapter-vercel/index.js
  packages/adapter-vercel/package.json
Labels: pkg:adapters

#620 make prefetching work
  .changeset/proud-sloths-exercise.md
  packages/kit/src/runtime/client/renderer.js
  packages/kit/src/runtime/client/router.js
  packages/kit/src/runtime/client/types.d.ts
  packages/kit/test/apps/basics/src/routes/routing/__tests__.js
  packages/kit/test/apps/basics/src/routes/routing/prefetched/index.json.js
  packages/kit/test/apps/basics/src/routes/routing/prefetched/index.svelte
Labels: bug

#635 Use a proxy to intercept responses, rather than a clone
  packages/kit/src/runtime/server/page.js
  packages/kit/test/apps/basics/src/routes/load/__tests__.js
  packages/kit/test/apps/basics/src/routes/load/index.svelte
  packages/kit/test/apps/basics/src/routes/load/large-response.svelte
Labels: bug

#656 Update realworld readme
  examples/realworld.svelte.dev/README.md
  examples/realworld.svelte.dev/logo.png
Labels: site / documentation

#677 Update example READMEs
  examples/hn.svelte.dev/README.md
  examples/realworld.svelte.dev/README.md
Labels: site / documentation

#681 Update realworld logo
  examples/realworld.svelte.dev/logo.png
Labels: site / documentation

#709 Some useful hints in migration docs
  documentation/migrating/02-pkg.md
  documentation/migrating/04-pages.md
Labels: site / documentation

#726 Global stylesheets (during `create-svelte` depending on the chosen CSS preprocessor)
  .changeset/wet-dingos-perform.md
  examples/hn.svelte.dev/src/app.css
  examples/hn.svelte.dev/src/routes/$layout.svelte
  examples/sandbox/src/app.css
  examples/sandbox/src/routes/$layout.svelte
  examples/sandbox/src/routes/index.svelte
  packages/create-svelte/cli/modifications/add_css.js
  packages/create-svelte/template-additions/src/app.css
  packages/create-svelte/template-additions/src/app.less
  packages/create-svelte/template-additions/src/app.scss
  packages/create-svelte/template/src/routes/$layout.svelte
  packages/create-svelte/template/src/routes/index.svelte
Labels: enhancement

#794 Fix client-side load error handling
  .changeset/beige-grapes-love.md
  packages/kit/src/runtime/client/renderer.js
  packages/kit/src/runtime/client/start.js
  packages/kit/src/runtime/client/types.d.ts
  packages/kit/src/runtime/server/page.js
  packages/kit/test/apps/basics/src/routes/$layout.svelte
  packages/kit/test/apps/basics/src/routes/preload/__tests__.js
Labels: error handling

#782 Clarified some documentation about cookies
  documentation/docs/01-routing.md
Labels: documentation
